fix: inexplicit small amount message when repay
aave/interface pull request #1679
Opened 2023-07-08 15:53 UTC by mishannn

## General Changes

- Fixed https://github.com/aave/interface/issues/1678

![Screenshot 2023-07-08 at 17 55 42](https://github.com/aave/interface/assets/15077672/cfb7674b-0044-43d0-895b-e90878429b07)

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [x]  The base branch is set to `main`
- [x]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [ ]  The Github issue has been linked to the PR in the Development section
- [x]  The General Changes section has been filled out
- [ ]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [ ]  The PR is in `Open` state and not in `Draft` mode
- [ ]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

2023-07-26 15:49 UTC, grothem approved these changes
Thanks for the PR! Looks good!

2023-07-28 06:17 UTC, defispartan submitted a review, later dismissed

2023-07-28 16:57 UTC, grothem commented
@mishannn could you merge latest main in?

There's a new `useDebtSwitch` hook that will need to be updated after you merge, replacing `MESSAGE_MAP` with `convertParaswapErrorMessage`

2023-08-07 17:30 UTC, mishannn commented
@grothem done!

2023-08-07 20:40 UTC, grothem requested changes
Thanks @mishannn,

After doing some testing, I realized the error message doesn't make sense in the case of collateral and debt switch. Could you update the message? We should be able to get this merged after that update.

Thanks again!

2023-08-07 20:40 UTC, grothem commented on src/hooks/paraswap/common.ts
> +    message: 'Repay amount is too small. Please try larger amount.',
Update message to be:

`Amount is too small. Please try larger amount.`

2023-08-08 07:50 UTC, mishannn commented
@grothem done!

2023-08-08 20:32 UTC, grothem approved these changes

2023-08-08 21:05 UTC, foodaka approved these changes
Thanks for the contribution @mishannn

2023-08-08 21:05 UTC, merged